#!/usr/bin/env perl

# Copyright (C) 2020-2025 Solution Libre
#
# This file is part of Pwnagotchi HDMI viewer.
#
# Pwnagotchi HDMI viewer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Pwnagotchi HDMI viewer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pwnagotchi HDMI viewer.  If not, see <https://www.gnu.org/licenses/>.

use Term::ReadKey;

$TIOCSTI = 0x5412;
$pid = `pgrep -n fbi`;
chomp($pid);
$tty = "/proc/$pid/fd/0";
$char = "j";
open($fh, ">", $tty);
ioctl($fh, $TIOCSTI, $char)

ReadMode('noecho');   # Turn off echo
ReadMode('raw');      # Set raw mode to prevent any signal handling

while (1) {
    if (defined(my $key = ReadKey(-1))) {   # Read a single character
        # Discard the input
    } else {
        last;   # Exit the loop when there's no more input
    }
}
