#!/bin/bash

# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

FILE=/root/pwnagotchi.png
TMP_FILE_1=/tmp/pwnagotchi-alias-1.png
TMP_FILE_2=/tmp/pwnagotchi-alias-2.png

trap "pkill fbi; exit" SIGINT SIGTERM SIGKILL

main() {
    fbi -T 1 -d /dev/fb0 -a -noverbose -cachemem 0 $FILE $TMP_FILE_1 $TMP_FILE_2
}

rm -f $TMP_FILE_1 && ln -s $FILE $TMP_FILE_1
rm -f $TMP_FILE_2 && ln -s $FILE $TMP_FILE_2
main

while :; do
    if [ -z "$(pgrep fbi)" ]; then
        main
    fi
    sleep 0.5
done
