#!/usr/bin/env sh

# Copyright (C) 2020-2025 Solution Libre
#
# This file is part of Pwnagotchi HDMI viewer.
#
# Pwnagotchi HDMI viewer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Pwnagotchi HDMI viewer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pwnagotchi HDMI viewer.  If not, see <https://www.gnu.org/licenses/>.

touch /root/.pwnagotchi-auto
cp /root/pwnagotchi-splashcreen.png /var/tmp/pwnagotchi/pwnagotchi.png
