#!/usr/bin/env bash

# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

PWD=$(pwd)
DIR=/var/tmp/pwnagotchi
FILE=pwnagotchi.png
ALIAS_FILE_1=pwnagotchi-alias-1.png
ALIAS_FILE_2=pwnagotchi-alias-2.png

trap "pkill fbi; exit" SIGINT SIGTERM SIGKILL

main() {
     fbi -T 1 -d /dev/fb0 -a -noverbose -cachemem 0 $FILE $ALIAS_FILE_1 $ALIAS_FILE_2
}

cd $DIR
rm -f $ALIAS_FILE_1 && ln -s $FILE $ALIAS_FILE_1
rm -f $ALIAS_FILE_2 && ln -s $FILE $ALIAS_FILE_2
main

while :; do
    if [ -z "$(pgrep fbi)" ]; then
        main
    fi
    sleep 0.5
done

cd $PWD
